---
- name: create rocky_docker
  hosts: server
  tasks:
    - name: updateOS
      shell: |
        dnf -y update
        dnf -y install epel-release
        dnf makecache
        grubby --update-kernel ALL --args selinux=0

    - name: install docker
      shell: |
        dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        dnf -y install docker-ce
        dnf -y install docker-ce-cli
        dnf -y install containerd.io
        systemctl enable --now docker

